### ISSUE TITLE
a few examples of how it is used?

### ISSUE THREAD

**Issue by mummyildiz** [imgen/Dakata#1]
a few examples of how it is used?

**Comment by imgen** [comment]
@mummyildiz sure, you are right. Will add them.

**Comment by imgen** [comment]
@mummyildiz a basic sample is added. Please take a look. More sample is on the way. Also I re-organized the code a bit to make it easier to read. I am going to add extensive comments as well. Stay tuned.

**Comment by imgen** [comment]
@mummyildiz this example is using SQL Server's sample database `WorldWideImporters`, you can import the database by downloading the `.bak` file from below link
https://github.com/microsoft/sql-server-samples/releases/tag/wide-world-importers-v1.0

**Comment by imgen** [comment]
@mummyildiz you probably need to change the connection string if you install your SQL Server on a different machine or don't use `Windows Authentication`

**Comment by mummyildiz** [comment]
Thank you for your interest. Great job, made my job easier.

**Comment by imgen** [comment]
@mummyildiz don't close the issue just yet. Examples are not complete yet. I'll reopen it.

**Comment by imgen** [comment]
@mummyildiz  Readme updated. It provides some general overview and guidelines. Are you familiar with how to make nuget packages? If so, and if you are interested, could you create nuget packages for the three libraries this repository has?

**Comment by mummyildiz** [comment]
I can add nuget packages.

**Comment by imgen** [comment]
@mummyildiz great. I will continue to focus on adding more examples, comments, and update readme if needed.

**Comment by imgen** [comment]
@mummyildiz I added you as a collaborator, you can directly make changes on this repository if you like.

**Comment by imgen** [comment]
@mummyildiz this is the invitation URL
https://github.com/imgen/Dakata/invitations

**Comment by mummyildiz** [comment]
Thank you
