### ISSUE TITLE
sqlkata logger ?

### ISSUE THREAD

**Issue by mummyildiz** [imgen/Dakata#2]
https://sqlkata.com/docs/execution/logging

We can add the Logger process in SqlKata. We use the IDbConnection class, the Logger process uses the QueryFactory class.
I tried but I need to change a lot of things and the structure is broken.

**Comment by imgen** [comment]
@mummyildiz sorry, was a bit busy lately. I will see what I can do.

**Comment by imgen** [comment]
@mummyildiz since we use `Dapper` to do the execution, not using `SqlKata.QueryFactory`, we can use our own version of `Logger`, instead of using `SqlKata.QueryFactory.Logger`

**Comment by imgen** [comment]
@mummyildiz logging support added. Please see the latest commit 
https://github.com/imgen/Dakata/commit/eadf9f804bb9b2733c345b973226d02a6226ec02
https://github.com/imgen/Dakata/commit/058a44c79d4035ffd0332d1abac663545751e6ea
https://github.com/imgen/Dakata/commit/134920c3e2e51448440d035bbe12854510de983c
https://github.com/imgen/Dakata/commit/c6805ffbade84b22b544001ec1321c4174bb14f8

Also added a logging example

**Comment by mummyildiz** [comment]
thank you. it was very good. I did trials.
